# Generated by Django 3.2.5 on 2021-07-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
