# Generated by Django 3.0.6 on 2020-08-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('cliente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Cliente')),
                ('documento', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Documento')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='server.Producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
    ]
