# Generated by Django 3.2.5 on 2021-07-18 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='proceso',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to=settings.AUTH_USER_MODEL),
        ),
    ]
