# Generated by Django 3.2.5 on 2021-07-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_proceso_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
