# Generated by Django 3.2.5 on 2021-07-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
