# Generated by Django 3.2.5 on 2021-07-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210705_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='documento',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='server.documento'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='producto',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='server.producto'),
        ),
    ]
