# Generated by Django 3.2.5 on 2021-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_delete_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='cantidad',
            field=models.FloatField(blank=True),
        ),
    ]
