# Generated by Django 3.2.5 on 2021-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_proceso_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
