# Generated by Django 3.2.5 on 2021-08-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_proceso_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='cliente',
        ),
    ]
